- hosts: windows_test
  gather_facts: no
  serial: 3
  
  vars_prompt:
    - name: domain_admin_username 
      prompt: "Domain Admin (bsp. admin@gutingia.local)"
      private: no
    - name: domain_admin_password
      prompt: "Admin passwort"
      private: yes

  vars:
    ansible_user: "{{ domain_admin_username }}"
    ansible_password: "{{ domain_admin_password }}"   

  tasks:
    - name: Create Folder wupatcher
      win_file:
        path: C:\temp\ansible\wupatcher
        state: directory
        force: yes

    - name: Copy powershell modules
      win_copy:
        src: ../powershell/modules
        dest: C:\Program Files\WindowsPowerShell

    - name: Copy powershell scripts
      win_copy:
        src: ../powershell/scripts
        dest: C:\temp\ansible\wupatcher

    - name: Führe PowerShell-Skript aus
      win_shell: |
        C:\temp\ansible\wupatcher\scripts\Start.ps1
      register: ps_script_output
      environment:
        PSExecutionPolicyPreference: 'Bypass'

    - name: Zeige das Ergebnis des PowerShell-Skripts
      debug:
        var: ps_script_output.stdout_lines
