- name: Patch Linux Servers
  hosts: site
  become: yes

  tasks:
    - name: Dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Check reboot
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Autoremove
      ansible.builtin.apt:
        autoremove: yes

    - name: Autoclean
      ansible.builtin.apt:
        autoclean: yes
